### ISSUE TITLE
localhost:8080 not available in latest commit 

### ISSUE THREAD

**Issue by dfarmer** [relevance/labrepl#11]
I believe this is related to evjan's repl issue also. I'm using emacs/swank approach. 

The last working version I tried was tree 8f4903cbf32a522dc043 -- everything worked fine at that point. I'm guessing this is related to to the repl changes on 5-19-10. swank's output is below. 

The repl (in inferior-lisp mode and slime) works fine, I just can't access the web based tutorial anymore. If I run 'script/repl' it will not produce a working REPL, but it does load the web server. 

Clojure 1.2.0-master-SNAPSHOT
Starting swank...
WARNING: group-by already refers to: #'clojure.core/group-by in namespace: swank.util, being replaced by: #'swank.util/group-by
WARNING: group-by already refers to: #'clojure.core/group-by in namespace: swank.core, being replaced by: #'swank.util/group-by
WARNING: group-by already refers to: #'clojure.core/group-by in namespace: swank.util.concurrent.thread, being replaced by: #'swank.util/group-by
WARNING: group-by already refers to: #'clojure.core/group-by in namespace: swank.core.connection, being replaced by: #'swank.util/group-by
WARNING: group-by already refers to: #'clojure.core/group-by in namespace: swank.core.protocol, being replaced by: #'swank.util/group-by
WARNING: group-by already refers to: #'clojure.core/group-by in namespace: swank.util.io, being replaced by: #'swank.util/group-by
WARNING: group-by already refers to: #'clojure.core/group-by in namespace: swank.core.threadmap, being replaced by: #'swank.util/group-by
WARNING: group-by already refers to: #'clojure.core/group-by in namespace: swank.core.server, being replaced by: #'swank.util/group-by
WARNING: group-by already refers to: #'clojure.core/group-by in namespace: swank.util.net.sockets, being replaced by: #'swank.util/group-by
WARNING: group-by already refers to: #'clojure.core/group-by in namespace: swank.commands.basic, being replaced by: #'swank.util/group-by
WARNING: group-by already refers to: #'clojure.core/group-by in namespace: swank.commands.indent, being replaced by: #'swank.util/group-by
WARNING: group-by already refers to: #'clojure.core/group-by in namespace: swank.commands.completion, being replaced by: #'swank.util/group-by
WARNING: group-by already refers to: #'clojure.core/group-by in namespace: swank.commands.contrib, being replaced by: #'swank.util/group-by
WARNING: group-by already refers to: #'clojure.core/group-by in namespace: swank.commands.inspector, being replaced by: #'swank.util/group-by
user=> Connection opened on local port  4005
# <ServerSocket ServerSocket[addr=0.0.0.0/0.0.0.0,port=0,localport=4005]>

WARNING: spit already refers to: #'clojure.core/spit in namespace: compojure.encodings, being replaced by: #'clojure.contrib.duck-streams/spit
WARNING: spit already refers to: #'clojure.core/spit in namespace: compojure.http.helpers, being replaced by: #'clojure.contrib.duck-streams/spit
WARNING: spit already refers to: #'clojure.core/spit in namespace: compojure.http.request, being replaced by: #'clojure.contrib.duck-streams/spit
WARNING: spit already refers to: #'clojure.core/spit in namespace: user, being replaced by: #'clojure.contrib.io/spit
java.lang.IllegalStateException: javadoc already refers to: #'clojure.java.javadoc/javadoc in namespace: user (run.clj:0)
user=>

**Comment by maxweber** [comment]
I think I have a similar problem. I'm using the clojure eclipse plugin.
Clojure 1.2.0-master-SNAPSHOT
1:1 user=> (require 'labrepl)
WARNING: spit already refers to: #'clojure.core/spit in namespace: compojure.encodings, being replaced by: #'clojure.contrib.duck-streams/spit
WARNING: spit already refers to: #'clojure.core/spit in namespace: compojure.http.helpers, being replaced by: #'clojure.contrib.duck-streams/spit
WARNING: spit already refers to: #'clojure.core/spit in namespace: compojure.http.request, being replaced by: #'clojure.contrib.duck-streams/spit
nil
1:2 user=> (labrepl/-main)
WARNING: spit already refers to: #'clojure.core/spit in namespace: user, being replaced by: #'clojure.contrib.io/spit
java.lang.IllegalStateException: javadoc already refers to: #'clojure.java.javadoc/javadoc in namespace: user (repl-1:2)
1:3 user=>

**Comment by stuarthalloway** [comment]
Thanks! Should be fixed by http://github.com/relevance/labrepl/commit/5e7b95824c278e6ed93a008d6e0c6e8fdcfba56f

**Comment by dfarmer** [comment]
That did it. Thanks!
