### ISSUE TITLE
IntelliJ error when starting the REPL

### ISSUE THREAD

**Issue by evjan** [relevance/labrepl#12]
I'm using IntelliJ Community Edition on a Windows 7 box.

I've followed the instructions for setting up the IntelliJ environment, and when I type (require 'labrepl) in the REPL, i get the following error message:

Clojure 1.2.0-master-SNAPSHOT
user=> (require 'labrepl)
WARNING: reader macro ^ is deprecated; use meta instead
java.lang.RuntimeException: java.lang.IllegalArgumentException: Don't know how to create ISeq from: clojure.lang.Symbol (labrepl.clj:1)

**Comment by abedra** [comment]
Try updating the project and dependencies and running again.  I just installed the latest version of IntelliJ community edition on Windows 7, followed the instructions and everything worked just fine for me

**Comment by perdalum** [comment]
I'm running the newest IntelliJ Ultimate edition 9.0.2, newest La Clojure plugin and pulled the newest labrepl - everything on XP. 

I get the exact same error as evjan.

The same labrepl checkout runs fine from CMD.EXE.

If I try (. javax.swing.JOptionPane (showMessageDialog nil "Hello World")) in the IntelliJ REPL, I get errors abount missing awt.dll.

Alas, I guess that something awry is affot with the IntelliJ/La Clojure setup.

abedra, did you do the setup on a totally clean IntelliJ and La Clojure setup? Which version of InteliJ and La Clojure have you installed?

**Comment by abedra** [comment]
You should use IntelliJ to check the code out instead of cmd.  IntelliJ does some automagic importing of the project and puts the right things in the right places in order to function.  The instructions are in the labrepl README for doing so inside of IntelliJ

**Comment by abedra** [comment]
I have tried this on Windows 7, Ubuntu 10.04, and Snow Leopard on Ultimate Edition and none of them have had this issue. I suggest clearing out your IntelliJ install and settings and trying again.  I am closing this issue for now.  If you can find an easy way to reproduce the bug please reopen and send me a message.
