### ISSUE TITLE
build fails: can't find clojure-contrib-1.2.0-master-SNAPSHOT.jar 

### ISSUE THREAD

**Issue by gw666** [relevance/labrepl#14]
I can't find clojure-contrib-1.2.0-master-SNAPSHOT.jar anywhere on the web, so I'm stuck. Here's the full output. Thanks for your help.  --gw

NetBeans: Executing 'mvn.bat -Dnetbeans.execution=true install'
NetBeans:      JAVA_HOME=C:\Program Files\Java\jdk1.6.0_20
## Scanning for projects...

Building labrepl
##    task-segment: [install]

[resources:resources]
[WARNING] Using platform encoding (Cp1252 actually) to copy filtered resources, i.e. build is platform dependent!
skip non existing resourceDirectory C:\tech\clojurestuff\RelevanceLabRepl\src\main\resources
Downloading: http://build.clojure.org/releases/org/clojure/clojure-contrib/1.2.0-master-SNAPSHOT/clojure-contrib-1.2.0-master-SNAPSHOT.pom
Unable to find resource 'org.clojure:clojure-contrib:pom:1.2.0-master-SNAPSHOT' in repository clojure-releases (http://build.clojure.org/releases)
Downloading: http://repo.incanter.org/org/clojure/clojure-contrib/1.2.0-master-SNAPSHOT/clojure-contrib-1.2.0-master-SNAPSHOT.pom
Unable to find resource 'org.clojure:clojure-contrib:pom:1.2.0-master-SNAPSHOT' in repository incanter (http://repo.incanter.org)
Downloading: http://repo1.maven.org/maven2/org/clojure/clojure-contrib/1.2.0-master-SNAPSHOT/clojure-contrib-1.2.0-master-SNAPSHOT.pom
Unable to find resource 'org.clojure:clojure-contrib:pom:1.2.0-master-SNAPSHOT' in repository central (http://repo1.maven.org/maven2)
Downloading: http://build.clojure.org/releases/org/clojure/clojure-contrib/1.2.0-master-SNAPSHOT/clojure-contrib-1.2.0-master-SNAPSHOT.pom
Unable to find resource 'org.clojure:clojure-contrib:pom:1.2.0-master-SNAPSHOT' in repository clojure (http://build.clojure.org/releases)
Downloading: http://build.clojure.org/snapshots/org/clojure/clojure-contrib/1.2.0-master-SNAPSHOT/clojure-contrib-1.2.0-master-SNAPSHOT.pom
Unable to find resource 'org.clojure:clojure-contrib:pom:1.2.0-master-SNAPSHOT' in repository clojure-snapshots (http://build.clojure.org/snapshots)
Downloading: http://clojars.org/repo//org/clojure/clojure-contrib/1.2.0-master-SNAPSHOT/clojure-contrib-1.2.0-master-SNAPSHOT.pom
Unable to find resource 'org.clojure:clojure-contrib:pom:1.2.0-master-SNAPSHOT' in repository clojars (http://clojars.org/repo/)
Downloading: http://build.clojure.org/releases/org/clojure/clojure-contrib/1.2.0-master-SNAPSHOT/clojure-contrib-1.2.0-master-SNAPSHOT.jar
Unable to find resource 'org.clojure:clojure-contrib:jar:1.2.0-master-SNAPSHOT' in repository clojure-releases (http://build.clojure.org/releases)
Downloading: http://repo.incanter.org/org/clojure/clojure-contrib/1.2.0-master-SNAPSHOT/clojure-contrib-1.2.0-master-SNAPSHOT.jar
Unable to find resource 'org.clojure:clojure-contrib:jar:1.2.0-master-SNAPSHOT' in repository incanter (http://repo.incanter.org)
Downloading: http://repo1.maven.org/maven2/org/clojure/clojure-contrib/1.2.0-master-SNAPSHOT/clojure-contrib-1.2.0-master-SNAPSHOT.jar
Unable to find resource 'org.clojure:clojure-contrib:jar:1.2.0-master-SNAPSHOT' in repository central (http://repo1.maven.org/maven2)
Downloading: http://build.clojure.org/releases/org/clojure/clojure-contrib/1.2.0-master-SNAPSHOT/clojure-contrib-1.2.0-master-SNAPSHOT.jar
Unable to find resource 'org.clojure:clojure-contrib:jar:1.2.0-master-SNAPSHOT' in repository clojure (http://build.clojure.org/releases)
Downloading: http://build.clojure.org/snapshots/org/clojure/clojure-contrib/1.2.0-master-SNAPSHOT/clojure-contrib-1.2.0-master-SNAPSHOT.jar
Unable to find resource 'org.clojure:clojure-contrib:jar:1.2.0-master-SNAPSHOT' in repository clojure-snapshots (http://build.clojure.org/snapshots)
Downloading: http://clojars.org/repo//org/clojure/clojure-contrib/1.2.0-master-SNAPSHOT/clojure-contrib-1.2.0-master-SNAPSHOT.jar
## [ERROR]BUILD ERROR

Failed to resolve artifact.
## Missing:

1) org.clojure:clojure-contrib:jar:1.2.0-master-SNAPSHOT

  Try downloading the file manually from the project website.

  Then, install it using the command: 
      mvn install:install-file -DgroupId=org.clojure -DartifactId=clojure-contrib -Dversion=1.2.0-master-SNAPSHOT -Dpackaging=jar -Dfile=/path/to/file

  Alternatively, if you host your own repository you can deploy the file there: 
      mvn deploy:deploy-file -DgroupId=org.clojure -DartifactId=clojure-contrib -Dversion=1.2.0-master-SNAPSHOT -Dpackaging=jar -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]

  Path to dependency: 
          1) labrepl:labrepl:jar:0.0.1
          2) org.clojure:clojure-contrib:jar:1.2.0-master-SNAPSHOT

---

1 required artifact is missing.

for artifact: 
  labrepl:labrepl:jar:0.0.1

from the specified remote repositories:
  central (http://repo1.maven.org/maven2),
  clojars (http://clojars.org/repo/),
  incanter (http://repo.incanter.org),
  clojure-snapshots (http://build.clojure.org/snapshots),
  clojure (http://build.clojure.org/releases),
  clojure-releases (http://build.clojure.org/releases)

---
## For more information, run Maven with the -e switch

Total time: 4 seconds
Finished at: Sat Jun 26 19:17:59 PDT 2010
## Final Memory: 9M/23M

**\* end of output ***

**Comment by abedra** [comment]
I was able to reproduce this issue on netbeans 6.8.  I am not 100% sure what is wrong here, but I will dig in and see if I can figure it out.  As for the clojure-1.2.0-master-SNAPSHOT jar it is available from a variety of sources.  If you take a look at the project.clj file in labrepl you can gather the information you need.

**Comment by heow** [comment]
Unable to reproduce with straight-up Maven.  TODO: test with Netbeans 6.9, see new setup instructions in README.

**Comment by abedra** [comment]
If you are using netbeans 6.9.1, it seems you have to use the Java SE bundle to avoid issues.  If you follow the new README instructions for netbeans you should be ok.
