### ISSUE TITLE
maven error

### ISSUE THREAD

**Issue by victorbstan** [relevance/labrepl#19]
victor-stans-imac:labrepl victorstan$ mvn clojure:repl
[INFO] Scanning for projects...
[INFO] Searching repository for plugin with prefix: 'clojure'.
[INFO] org.apache.maven.plugins: checking for updates from central
[INFO] org.codehaus.mojo: checking for updates from central
[INFO] artifact org.apache.maven.plugins:maven-clojure-plugin: checking for updates from central
[INFO] ------------------------------------------------------------------------
[ERROR] BUILD ERROR
[INFO] ------------------------------------------------------------------------
[INFO] The plugin 'org.apache.maven.plugins:maven-clojure-plugin' does not exist or no valid version could be found
[INFO] ------------------------------------------------------------------------
[INFO] For more information, run Maven with the -e switch
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 7 seconds
[INFO] Finished at: Thu Jul 22 01:24:10 EDT 2010
[INFO] Final Memory: 3M/81M
[INFO] --------------------------

**Comment by abedra** [comment]
Running this on Windows 7 and OS X Snow Leopard and Ubuntu 10.04 with the most recent labrepl seems to work without any issues.  Please make sure you have things updated and that your internet connection is not blocking anything.

**Comment by victorbstan** [comment]
I got it working with Eclipse IDE tutorial, but not with comand line or with intelliJ IDEA
