### ISSUE TITLE
Eclipse/Counterclockwise: Could not calculate build plan

### ISSUE THREAD

**Issue by bradfordw** [relevance/labrepl#2]
Hi there, when trying to import the labrepl maven project I keep getting "Could not calculate build plan"

The event details can be found here: http://gist.github.com/359023

I don't believe I'm missing any steps prior to importing the project, perhaps there is something obvious that I'm missing?

**Comment by abedra** [comment]
What versions of things are you using?  I downloaded Eclipse Helios on a brand new machine and followed the instructions from README.markdown and things started right up.  If you can give me the versions you are using I will see if I can track down the issue there.

**Comment by bradfordw** [comment]
I'll give it another shot and see what (if any) issues I have this time around.

**Comment by bradfordw** [comment]
Works as intended!
