### ISSUE TITLE
unexpected output in the min-1 function in the clojure labs

### ISSUE THREAD

**Issue by cervatz** [relevance/labrepl#22]
Unexpected output of the following function in the labs/looping page in the clojure labs web application

(defn min-1
  [x & more](loop [min x
         more %28seq more%29]
    %28if-let [x %28first more%29]
      %28recur %28if %28< x min%29 x min%29 %28next more%29%29
      min%29))

I would expect it to return the minimum value of the vector, but it returns the whole vector. 

I am a total beginner with clojure so I apologize for any stupid comment. But if this code really does not work maybe it is good to fix it, because many people might be trying to learn clojure with the labrepl clojure labs.

Thank you!

**Comment by stuarthalloway** [comment]
Check the signature: min-1 doesn't take a vector, it takes a variable length sequence of args:

(min-1 1 -3 5) => -3

**Comment by cervatz** [comment]
Thank you very much!
