### ISSUE TITLE
Cannot run in La Clojure

### ISSUE THREAD

**Issue by Plummtw** [relevance/labrepl#23]
user=> (require 'labrepl)
java.io.FileNotFoundException: Could not locate compojure__init.class or compojure.clj on classpath:  (labrepl.clj:1)

but the compojure is there....

user=> (println (seq (.getURLs (java.lang.ClassLoader/getSystemClassLoader)))) 
(#<URL file:/C:/Program%3fFiles/Java/jdk1.6.0_14/jre/lib/alt-rt.jar> #<URL file:/C:/Program%3fFiles/Java/jdk1.6.0_14/jre/lib/charsets.jar> #<URL file:/C:/Program%3fFiles/Java/jdk1.6.0_14/jre/lib/deploy.jar> #<URL file:/C:/Program%3fFiles/Java/jdk1.6.0_14/jre/lib/javaws.jar> #<URL file:/C:/Program%3fFiles/Java/jdk1.6.0_14/jre/lib/jce.jar> #<URL file:/C:/Program%3fFiles/Java/jdk1.6.0_14/jre/lib/jsse.jar> #<URL file:/C:/Program%3fFiles/Java/jdk1.6.0_14/jre/lib/management-agent.jar> #<URL file:/C:/Program%3fFiles/Java/jdk1.6.0_14/jre/lib/plugin.jar> #<URL file:/C:/Program%3fFiles/Java/jdk1.6.0_14/jre/lib/resources.jar> #<URL file:/C:/Program%3fFiles/Java/jdk1.6.0_14/jre/lib/rt.jar> #<URL file:/C:/Program%3fFiles/Java/jdk1.6.0_14/jre/lib/ext/dnsns.jar> #<URL file:/C:/Program%3fFiles/Java/jdk1.6.0_14/jre/lib/ext/localedata.jar> #<URL file:/C:/Program%3fFiles/Java/jdk1.6.0_14/jre/lib/ext/sunjce_provider.jar> #<URL file:/C:/Program%3fFiles/Java/jdk1.6.0_14/jre/lib/ext/sunmscapi.jar> #<URL file:/C:/Program%3fFiles/Java/jdk1.6.0_14/jre/lib/ext/sunpkcs11.jar> #<URL file:/D:/temp/clojure-1.2.0-RC1/clojure.jar> #<URL file:/D:/temp/clojure-contrib-1.2.0-RC1/target/clojure-contrib-1.2.0-RC1.jar> #<URL file:/D:/lang/clojure11/labrepl2/labrepl/target/classes> #<URL file:/C:/Documents%3fand%3fSettings/Plummtw/.m2/repository/org/clojure/clojure/1.2.0-master-SNAPSHOT/clojure-1.2.0-master-SNAPSHOT.jar> #<URL file:/C:/Documents%3fand%3fSettings/Plummtw/.m2/repository/org/clojure/clojure-contrib/1.2.0-SNAPSHOT/clojure-contrib-1.2.0-SNAPSHOT.jar> #<URL file:/C:/Documents%3fand%3fSettings/Plummtw/.m2/repository/org/clojars/stuarthalloway/compojure/0.3.3-SNAPSHOT/compojure-0.3.3-SNAPSHOT.jar> #<URL file:/C:/Documents%3fand%3fSettings/Plummtw/.m2/repository/commons-codec/commons-codec/1.3/commons-codec-1.3.jar> #<URL file:/C:/Documents%3fand%3fSettings/Plummtw/.m2/repository/commons-io/commons-io/1.4/commons-io-1.4.jar> #<URL file:/C:/Documents%3fand%3fSettings/Plummtw/.m2/repository/commons-fileupload/commons-fileupload/1.2.1/commons-fileupload-1.2.1.jar> #<URL file:/C:/Documents%3fand%3fSettings/Plummtw/.m2/repository/org/mortbay/jetty/jetty/6.1.21/jetty-6.1.21.jar> #<URL file:/C:/Documents%3fand%3fSettings/Plummtw/.m2/repository/org/mortbay/jetty/jetty-util/6.1.21/jetty-util-6.1.21.jar> #<URL file:/C:/Documents%3fand%3fSettings/Plummtw/.m2/repository/org/mortbay/jetty/servlet-api/2.5-20081211/servlet-api-2.5-20081211.jar> #<URL file:/C:/Documents%3fand%3fSettings/Plummtw/.m2/repository/postgresql/postgresql/8.4-701.jdbc4/postgresql-8.4-701.jdbc4.jar> #<URL file:/C:/Documents%3fand%3fSettings/Plummtw/.m2/repository/log4j/log4j/1.2.14/log4j-1.2.14.jar> #<URL file:/C:/Documents%3fand%3fSettings/Plummtw/.m2/repository/org/incanter/incanter-full/1.2.0-SNAPSHOT/incanter-full-1.2.0-SNAPSHOT.jar> #<URL file:/C:/Documents%3fand%3fSettings/Plummtw/.m2/repository/org/incanter/incanter-core/1.2.0-SNAPSHOT/incanter-core-1.2.0-SNAPSHOT.jar> #<URL file:/C:/Documents%3fand%3fSettings/Plummtw/.m2/repository/incanter/parallelcolt/0.7.2/parallelcolt-0.7.2.jar> #<URL file:/C:/Documents%3fand%3fSettings/Plummtw/.m2/repository/incanter/netlib-java/0.9.1/netlib-java-0.9.1.jar> #<URL file:/C:/Documents%3fand%3fSettings/Plummtw/.m2/repository/incanter/arpack-combo/0.1/arpack-combo-0.1.jar> #<URL file:/C:/Documents%3fand%3fSettings/Plummtw/.m2/repository/org/incanter/incanter-io/1.2.0-SNAPSHOT/incanter-io-1.2.0-SNAPSHOT.jar> #<URL file:/C:/Documents%3fand%3fSettings/Plummtw/.m2/repository/org/incanter/incanter-chrono/1.2.0-SNAPSHOT/incanter-chrono-1.2.0-SNAPSHOT.jar> #<URL file:/C:/Documents%3fand%3fSettings/Plummtw/.m2/repository/joda-time/joda-time/1.6/joda-time-1.6.jar> #<URL file:/C:/Documents%3fand%3fSettings/Plummtw/.m2/repository/net/sf/opencsv/opencsv/2.0.1/opencsv-2.0.1.jar> #<URL file:/C:/Documents%3fand%3fSettings/Plummtw/.m2/repository/org/danlarkin/clojure-json/1.1-SNAPSHOT/clojure-json-1.1-SNAPSHOT.jar> #<URL file:/C:/Documents%3fand%3fSettings/Plummtw/.m2/repository/org/incanter/incanter-processing/1.2.0-SNAPSHOT/incanter-processing-1.2.0-SNAPSHOT.jar> #<URL file:/C:/Documents%3fand%3fSettings/Plummtw/.m2/repository/incanter/processing-core/1/processing-core-1.jar> #<URL file:/C:/Documents%3fand%3fSettings/Plummtw/.m2/repository/org/incanter/incanter-charts/1.2.0-SNAPSHOT/incanter-charts-1.2.0-SNAPSHOT.jar> #<URL file:/C:/Documents%3fand%3fSettings/Plummtw/.m2/repository/incanter/jfreechart/1.0.13/jfreechart-1.0.13.jar> #<URL file:/C:/Documents%3fand%3fSettings/Plummtw/.m2/repository/incanter/jcommon/1.0.16/jcommon-1.0.16.jar> #<URL file:/C:/Documents%3fand%3fSettings/Plummtw/.m2/repository/incanter/gnujaxp/1/gnujaxp-1.jar> #<URL file:/C:/Documents%3fand%3fSettings/Plummtw/.m2/repository/org/incanter/incanter-mongodb/1.2.0-SNAPSHOT/incanter-mongodb-1.2.0-SNAPSHOT.jar> #<URL file:/C:/Documents%3fand%3fSettings/Plummtw/.m2/repository/congomongo/congomongo/0.1.2-SNAPSHOT/congomongo-0.1.2-SNAPSHOT.jar> #<URL file:/C:/Documents%3fand%3fSettings/Plummtw/.m2/repository/org/clojars/somnium/mongo-java-driver/1.1.0-SNAPSHOT/mongo-java-driver-1.1.0-SNAPSHOT.jar> #<URL file:/C:/Documents%3fand%3fSettings/Plummtw/.m2/repository/org/clojars/somnium/clojure-db-object/0.1.1-SNAPSHOT/clojure-db-object-0.1.1-SNAPSHOT.jar> #<URL file:/C:/Documents%3fand%3fSettings/Plummtw/.m2/repository/org/incanter/incanter-pdf/1.2.0-SNAPSHOT/incanter-pdf-1.2.0-SNAPSHOT.jar> #<URL file:/C:/Documents%3fand%3fSettings/Plummtw/.m2/repository/com/lowagie/itext/1.4/itext-1.4.jar> #<URL file:/C:/Documents%3fand%3fSettings/Plummtw/.m2/repository/antlr/stringtemplate/2.2/stringtemplate-2.2.jar> #<URL file:/C:/Documents%3fand%3fSettings/Plummtw/.m2/repository/antlr/antlr/2.7.2/antlr-2.7.2.jar> #<URL file:/C:/Documents%3fand%3fSettings/Plummtw/.m2/repository/clojure-http-client/clojure-http-client/1.0.0-SNAPSHOT/clojure-http-client-1.0.0-SNAPSHOT.jar> #<URL file:/C:/Documents%3fand%3fSettings/Plummtw/.m2/repository/jline/jline/0.9.94/jline-0.9.94.jar> #<URL file:/C:/Documents%3fand%3fSettings/Plummtw/.m2/repository/junit/junit/3.8.1/junit-3.8.1.jar> #<URL file:/C:/Documents%3fand%3fSettings/Plummtw/.m2/repository/circumspec/circumspec/0.0.10/circumspec-0.0.10.jar> #<URL file:/C:/Documents%3fand%3fSettings/Plummtw/.m2/repository/swank-clojure/swank-clojure/1.1.0-SNAPSHOT/swank-clojure-1.1.0-SNAPSHOT.jar> #<URL file:/C:/Documents%3fand%3fSettings/Plummtw/.IntelliJIdea90/config/plugins/clojure-plugin/lib/clojure.jar> #<URL file:/D:/lang/clojure11/labrepl2/labrepl/test/> #<URL file:/D:/lang/clojure11/labrepl2/labrepl/src/>)
nil

**Comment by catharinejm** [comment]
Tested in latest master (9/30/2010). Started without issue.
