### ISSUE TITLE
swank is not added to classpath when running script/swank

### ISSUE THREAD

**Issue by rbolkey** [relevance/labrepl#24]
The script/repl only add the jars immediately under "lib" but not "lib/dev" where the swank-clojure jar is located.  That needs to be added to the classpath for script/swank to work; unless, of course, it was already supposed to be on the classpath somehow?

**Comment by rbolkey** [comment]
Note: using the emacs environment if that affects the issue.

**Comment by catharinejm** [comment]
Swank-clojure is no longer a dev-dependency so it's in lib/ rather than lib/dev/.
