### ISSUE TITLE
Selecting multi-lines of code on web pages includes the line numbers...

### ISSUE THREAD

**Issue by franks42** [relevance/labrepl#25]
...which makes the simple copy&pasting of code-snippets a royal pain...

The issue is the use of the old version of SyntaxHighlighter - the latest and greatest doesn't include the line numbers anymore!
When I tried to make it work with the new SyntaxHighlighter 3.0.83, I found out that it also relies on XRegExp. The following recipe made it work for me:

Download SyntaxHighlighter version 3.0.83 from:
http://alexgorbatchev.com/SyntaxHighlighter/download/

In the labrepl source tree,
replace "shCore.js" in labrepl/public/javascript/ with new version from SH
replace "shCore.css" and "shThemeDefault.css" in labrepl/public/stylesheets/ with new versions from SH

Download "xregexp.js" from XRegExp at http://xregexp.com/
In the labrepl source tree,
add "xregexp.js" to labrepl/public/javascript/

In "labrepl/src/labrepl/web.clj"
add "/javascripts/xregexp.js" to vector "default-javascripts"
such that assignment looks like:

(def default-javascripts
  ["/javascripts/jquery.js"
   "/javascripts/application.js"
   "/javascripts/xregexp.js"
   "/javascripts/shCore.js"
   "/javascripts/shBrushClojure.js"])

Done - reload and run the web server, and if all went well... select multi-lines of code without the line numbers for easy copy&pasting in the repl!

**Comment by abedra** [comment]
Fixed in f7d6a4cbbbabdad17882fdcb49ce93cfff4c96a2.  Instead of adding the xregexp library I just turned off the gutters.

**Comment by franks42** [comment]
What ever works ;-)
Thanks for addressing this "convenience" issue.
