### ISSUE TITLE
User input in a cmd.exe window is not echoed before pressing enter.

### ISSUE THREAD

**Issue by piyo** [relevance/labrepl#26]
I installed this program using the "Getting Started (Maven)" instructions. My environment is Windows XP 32bit with Java 1.6.0 and Maven 2.2.1 and msysgit 1.6.5.1. I am at step 4. I can now see the website at localhost:8080. I navigate to the first page and then shift my focus back to the cmd.exe window. I see this in the window:

Welcome to the labrepl. Browse to localhost:8080 to get started!
user=> log4j:WARN No appenders could be found for logger (labrepl).
log4j:WARN Please initialize the log4j system properly.

I try typing (println "hello world") but nothing is echoed. I cannot see what I just typed. I then hit the Enter key and the input and result is shown.

**Comment by abedra** [comment]
This is not an issue with labrepl.  This is an issue with the windows terminal emulator.  I tried it on Windows 7 and don't get that behavior.  I suggest trying this in the cygwin terminal.

**Comment by piyo** [comment]
Then I suggest that the README.markdown file should mention Cygwin as a prerequisite to installing.
