### ISSUE TITLE
its-all-data needs to be updated for exception generated using default calculations

### ISSUE THREAD

**Issue by donmullen** [relevance/labrepl#31]
1. Clojure integer literals are not limited to the range of Java's primitive types. They can be any size, and Clojure will choose the correct underlying representation.

This is no longer true in clojure 1.3.0 - we should expand lab to include (*' x y) or drop and move to different lab.

**Comment by abedra** [comment]
The project has moved back to 1.2.0 because of some conflicts in contrib.  Closing this for now
