### ISSUE TITLE
Symbols &gt; instead of > are shown

### ISSUE THREAD

**Issue by oleg** [relevance/labrepl#33]
On page /labs/intro symbols &gt; instead of > are shown.
Macros 'code' replaces '>' and '<'  with '&gt;' and '&lt;' but inside CDATA we shouldn't do it.

**Comment by heow** [comment]
This is probably a result of the fix for #8, which was put in to support nested CDATAs.

**Comment by abedra** [comment]
Fixed as of c35b6f7092522b126cd3520564ea1eef90defc1c
