### ISSUE TITLE
Missing artifact (dependencies of incanter)

### ISSUE THREAD

**Issue by beloglazov** [relevance/labrepl#37]
Hello,

I'm trying to run the project in Eclipse with Counterclockwise, but I get the following errors:

10/29/10 11:15:58 AM IST: Missing artifact commons-logging:commons-logging:jar:1.1:runtime
10/29/10 11:15:58 AM IST: Missing artifact logkit:logkit:jar:1.0.1:runtime
10/29/10 11:15:58 AM IST: Missing artifact avalon-framework:avalon-framework:jar:4.1.3:runtime

These are dependencies of incanter:incanter:1.2.3-SNAPSHOT

How can I resolve the problem? 

Thanks,
Anton

**Comment by abedra** [comment]
Incanter has been updated to 1.2.3 release.  This should fix the issue
