### ISSUE TITLE
updating the windows cmdline section of the readme

### ISSUE THREAD

**Issue by pbuckley-personal** [relevance/labrepl#38]
I had a question on how to update this section of the readme for labrepl in light of a few recent changes:
1. `lein self-install` is now supported on Windows
2. It says to download the latest clojure jar (1.3.1-alpha) but the latest project.clj that I pull down from github has clojure 1.2 - either the project.clj should be updated, and we just run `lein deps`, or is downloading clojure 1.3 and setting CLOJURE_JAR overriding the clojure jar in project.clj? If we use project.clj, can we do away with the "set CLOJURE_JAR"
3. I have leiningen-1.3.0, and it doesn't seem to have a {your-lein-install}\bin directory - I just have {your-lein-install} directory in my path so I can call lein.bat. 

> > > This is the section in question:
## Getting Started (Windows command line)

This is minimally tested. You are probably better off using Maven or one of the IDEs above. Let me know if you have problems.
- Make sure you have Java installed.
- Make sure you have
- [leiningen](http://github.com/technomancy/leiningen) installed. Do not use `lein self-install` as Windows installation is a manual process. You will need to:
- Download the leinigen.jar and set `LEIN_JAR` to point to it.
- Download [Clojure 1.3-alpha1](http://github.com/clojure/clojure/downloads)
- Set `CLOJURE_JAR` to point to the clojure.jar file.
- Set your path to include `{your-lein-install}\bin`
- Run `lein.bat deps` to install all the dependent libraries.
- Run `script\repl` to launch the labrepl.
- Browse to [http://localhost:8080](http://localhost:8080) for the labs.
- Press Ctrl+D to exit the repl when you are done.

**Comment by abedra** [comment]
This is a work in progress now.  I have started the move to 1.3 but it is a long road.  Once everything is worked out I will make the appropriate updates to the README
