### ISSUE TITLE
Suggestion for unified-update-model chapter

### ISSUE THREAD

**Issue by harishtella** [relevance/labrepl#39]
In the section for futures, someone new may try to run that first code block in the repl and face lots of frustration 

<code>(:use [clojure.http.client :only (request url-encode)]
          [clojure.contrib.json :only (read-json)]) 
</code>

running this in the repl gives you a:
java.lang.ClassNotFoundException: clojure.http.client (NO_SOURCE_FILE:8)

can it be changed to something like
<code>
(ns some-name-space
  (:use [clojure.http.client :only (request url-encode)])
  (:use [clojure.contrib.json :only (read-json)]))
</code>

or

<code>
(use '[clojure.http.client :only (request url-encode)]
     '[clojure.contrib.json :only (read-json)]
</code>

so that it works from a file or from the repl

**Comment by abedra** [comment]
I am working on ripping out clojure.http.client and replacing it with a simple Java API based solution.  clojure.http.client brings in dependencies that block the move to 1.3 and it really isn't required to make the labs work.

**Comment by abedra** [comment]
Ok this is all fixed up.  I changed things to use the REPL compatible version of use so that things are less confusing

**Comment by harishtella** [comment]
Thanks,

labrepl really helped me get going with clojure,

great work!
