### ISSUE TITLE
emacs instructions missing step

### ISSUE THREAD

**Issue by mch** [relevance/labrepl#4]
The instructions for using emacs in README.markdown are missing a step.  It is necessary to run `lein deps` before attempting to run `inferior-lisp`, as scripts\swank depends on the lib directory created by `lein deps`.

**Comment by mchampine** [comment]
Thanks Matt, a critical step!  I was getting ready to start manually installing packages and could have wasted hours.

**Comment by codification** [comment]
Ah, second time around I missed that step

**Comment by abedra** [comment]
Thanks for catching this.  I updated the readme in the emacs section.
