### ISSUE TITLE
Routes in mini-browser lab don't work with current Compojure

### ISSUE THREAD

**Issue by roerd** [relevance/labrepl#41]
The syntax for the routes in defroute has changed, and I can't find the serve-files function anywhere. After a lot of documentation reading and experimenting, I made it work with this definition (replacement for the code at the last step of section "Layout"):

```
(defroutes mockup-routes
  (GET "/m1" [] (mockup-1))
  (GET "/m2" [] (mockup-2))
  (GET "/m3" [] (mockup-3))
  (GET "/*" [*] (file-response * {:root "public"})))
```

**Comment by abedra** [comment]
This issue has been resolved
