### ISSUE TITLE
IntelliJ incanter on Ubuntu 10.10 - No X11 DISPLAY variable was set

### ISSUE THREAD

**Issue by pjgoodall** [relevance/labrepl#44]
I am up to the exercise: Its All Data/A Little Real Data/Step 8 
and got the following error (have included the steps to produce the 
error): 
        user=> (def words (read-lines "data/words")) 
        #'user/words 
        user=> (count words) 
        234936 
        user=> (use '[incanter core charts]) 
        nil 
        user=> (let 
            [f (frequencies (map first words))](view %28bar-chart %28keys f%29 %28vals f%29%29)) 
        java.awt.HeadlessException: 
        No X11 DISPLAY variable was set, but this program performed an 
        operation which requires it. (NO_SOURCE_FILE:0) 

I am on Ubuntu 10.10 Desktop - X11 is installed by default
Used this script to install pre-reqs before IntelliJ: 
        cd 
        sudo apt-get install python-software-properties 
        sudo apt-get update 
        sudo apt-get install sun-java6-jdk ant git tree maven2 
        sudo update-alternatives --config java 

Installed IntelliJ like this: 
        As described at https://github.com/relevance/labrepl 
        Used IntelliJ Community Edition - ideaIC-10.0.2.tar.gz 
        As IntelliJ was first started, an update of IntelliJ was allowed. 
        maven updates/build allowed to happen.

Cheers, 
--Peter G

**Comment by pjgoodall** [comment]
The above works on the same Ubuntu configuration with a fresh clone of labrepl and following the instructions for: 
    "Getting Started (Mac/Linux command line)"

**Comment by pjgoodall** [comment]
Apologies for the close/reopen - first time I've used github.

The "Getting Started (Maven)" version fails during build within the identical Ubuntu environment:

```
[ERROR] BUILD ERROR
[INFO] ------------------------------------------------------------------------
[INFO] The plugin 'org.apache.maven.plugins:maven-clojure-plugin' does not exist or no valid version could be found
```

**Comment by abedra** [comment]
This should be fixed now.  Leningen wiped out the clojure-maven plugin section of pom.xml when I regenerated it recently.  Thanks for reporting this.

**Comment by pjgoodall** [comment]
Hi Aaron,

I cloned labrepl, and imported it  again about 1/2 hour ago and just tested
- same error for me :-(
  I have attached a transcript from the IntelliJ Clojure console

Cheers,
--Peter Goodall

**Comment by abedra** [comment]
What you are seeing is not the maven error you reported above.  The fix I checked in was for the missing maven clojure repl plugin.  The error you are seeing now is due to your Ubuntu setup, not labrepl.

**Comment by pjgoodall** [comment]
The command-line version works "Getting Started (Mac/Linux command line)" - there is no problem there with X11. I have not touched X11 - plain install of 10.10 64-bit desktop Ubuntu. Not sure that a major standard distribution can be considered an error - unless there is a known bug.  What Linux distros has it been tested on with IntelliJ?
The only environment I have been able to get working with incanter is the Linux command-line. I have spent many days trying damned hard. I think this is meant to be beginner-level.

**Comment by abedra** [comment]
I'm on Ubuntu 10.10 64.  I use it as my daily development environment.  I just installed IntelliJ community edition 10 and checked out labrepl.  I used the maven browser and selected the clojure:repl task and everything worked successfully.  

This project is meant to be beginner level.  The problems you are experiencing are OS and editor specific.  If you can't get past this particular issue I suggest trying a different editor until you can get it sorted out.  There are lots of OS/Editor combinations out there.  Everyone sets their machines up a little different, and it can be difficult to diagnose what's actually going wrong.

I am going to consider this issue still closed.  If you do arrive at an answer please post it to the thread you opened on the mailing list and I will see if it should be added to the instructions.

**Comment by pjgoodall** [comment]
OK that's nice and clear. Thanks for your help....
