### ISSUE TITLE
Initializing error

### ISSUE THREAD

**Issue by boydb** [relevance/labrepl#5]
On Mac:

When running script/repl the following error occurs.

```
boyd-browns-macbook-pro:labrepl bnb$ script/repl
Clojure 1.2.0-master-SNAPSHOT
java.lang.ExceptionInInitializerError (control.clj:9)
user>
```

The repl works but Firefox gives an 'unable to connect' when trying to browse to http://localhost:8080

Could not find control.clj.

**Comment by hickst** [comment]
Stuart made a small update to the src/labrepl.clj file a couple hours ago but it still doesn't work for me -- I still get the exact same error you reported. I was able to hack up the pom.xml file to "drop-back" to version 1.1.0. This appears to work for now but I suspect I will encounter other problems as I progress through the lessons. If try hacking the pom file, don't forget to undo Stuart's latest change (io -> duck-streams).

**Comment by abedra** [comment]
I just gave this a try and didn't have any issues.  Can you try updating your local copy and trying again?  Don't forget to run lein deps before you start up script/repl.

**Comment by hickst** [comment]
It seems to be working fine now:
I started over from scratch: deleted and reinstalled leiningen, re-cloned labrepl and followed 'GettingStarted: Mac/Linux command line' instructions...success. I also followed the IntelliJ instructions with a successful result.
    Thanks for your help.

**Comment by abedra** [comment]
Thanks for confirming.  I'm closing this issue
