### ISSUE TITLE
Could not find or load main class jline.ConsoleRunner

### ISSUE THREAD

**Issue by palango** [relevance/labrepl#54]
When running script/repl after a fresh clone and lein deps I get this output:

> LANG=en_US script/repl
> Error: Could not find or load main class jline.ConsoleRunner

Any idea how to solve this?

**Comment by john2x** [comment]
I get this issue too but I'm on Windows 7. I followed the [Windows instructions in the wiki](https://github.com/relevance/labrepl/wiki/Windows) and got Leiningen running (`lein deps`, etc.), but running script/repl gives me this error.

**Comment by rigdern** [comment]
You can fix this by applying the change described here: https://github.com/relevance/labrepl/pull/53
