### ISSUE TITLE
Intellij - JDK step missing from docs, java.lang.NoClassDefFoundError: clojure/main

### ISSUE THREAD

**Issue by metaperl** [relevance/labrepl#9]
I repeat what I reported at http://groups.google.com/group/clojure/browse_thread/thread/87b42de9f763985f#

If you follow the labrepl instructions for Intellij IDEA, one part
says "just keep hitting next and accept defaults"

However, because no JDK(s) have been selected you get the following screen:
http://www.screencast.com/users/terrence_work/folders/Jing/media/87ff684d-8725-422f-8f9d-eda715505688

which I find confusing as a non-java programmer. I downloaded a java
jdk 1.6 from Sun and installed it, but it seems that also a JSDK
should be installed and I supposed the Intellij default one was fine.

But after doing those two steps and waiting for Maven to build some
things, I attempted
Tools > Clojure REPL > Add New Clojure REPL

and the new repl had the NoClassDef error when looking for clojure.main

so, if I was supposed to do more as far as installing JDK(s) I would
appreciate some specific instructions.

And I'm also guessing that I need to add clojure.jar to some sort of
java.library.path variable somehow, but dont know how to do that
either.

Screencast of adding the Java JDK and the Intellij JSDK as well as the
failing attempt to add a Clojure REPL is here:
http://www.screencast.com/users/terrence_work/folders/Jing/media/0fca5628-cca2-4811-b542-2d5dab8c9621

**Comment by abedra** [comment]
Instructions added to the README
